### ISSUE TITLE
F-Droid: change description

### ISSUE THREAD

**Issue by DC7IA** [meyerd/funktrainer#8]
The description on F-Droid uses the term "ham radio" instead of the proper name "amateur radio".

This makes it hard to find the app as it does not show up when searching for "amateur radio", this should be fixed.

**Comment by meyerd** [comment]
Hi, 
I always was under the impression, that "ham radio" is the correct translation for "Amateurfunk" but turns out, you are well half-right ;). "Ham Radio" apparently is the colloquial term, whereas "amateur radio" might be more correct. I'll have to figure out the f-droid metadata file structure thingy to update the texts.

**Comment by linsui** [comment]
The short_description should be shorter than 80 charactors. It will be truncated.

Would you like to also add long_descriptions and maintain other locales in your repo? They are in https://gitlab.com/fdroid/fdroiddata/-/tree/f2bf885c969bbf872bfc9dfdbc3e082a5412f4c8/metadata/de.hosenhasser.funktrainer.
